version: '3.8'
name: category-feature

services:
  category-postgres:
    image: postgres:14.2
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=category
    volumes:
      - ./init-extension.sh:/docker-entrypoint-initdb.d/init-extension.sh
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  category-test-postgres:
    image: postgres:14.2
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=category-test
    volumes:
      - ./init-extension.sh:/docker-entrypoint-initdb.d/init-extension.sh
