version: '3.8'
name: category-ltree
volumes:
  pg_storage:

services:
  category-postgres:
    image: postgres:14.2
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=category
    volumes:
      - pg_storage:/var/lib/postgresql/data
      - ./init-extension.sh:/docker-entrypoint-initdb.d/init-extension.sh
  category-test-postgres:
    image: postgres:14.2
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=category
    volumes:
      - pg_storage:/var/lib/postgresql/data
      - ./init-extension.sh:/docker-entrypoint-initdb.d/init-extension.sh
